apiVersion: v1
kind: Service
metadata:
  name: stock-tech-candlestick-service
spec:
  selector:
    app: stock-tech-candlestick
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
