---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-tech-candlestick
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/stock-tech-candlestick.git
    targetRevision: HEAD
    path: charts/stock-tech-candlestick
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
