apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-tech-candlestick
  labels:
    app: stock-tech-candlestick
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: stock-tech-candlestick
  template:
    metadata:
      labels:
        app: stock-tech-candlestick
    spec:
      containers:
        - name: stock-tech-candlestick
          image: "{ { .Values.image.repository } }:{ { .Values.image.tag } }"
          ports:
            - containerPort: 8080
