replicaCount: 1

image:
  repository: your-registry/stock-tech-candlestick
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer # Default to LoadBalancer, but can be ClusterIP/NodePort
  port: 80
  targetPort: 8000

environment:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  RABBITMQ_HOST: "stock-tech-candlestick-rabbitmq.prod.internal"
  RABBITMQ_QUEUE: "stock-tech-candlestick_queue"
