---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namespace: default

labels:
  - includeSelectors: true
    pairs:
      app: stock-tech-candlestick

images:
  - name: stock-tech-candlestick
    newName: stock-tech-candlestick
    newTag: latest

patchesStrategicMerge:
  - # patch-deployment.yaml
